-- jeden rekord wprawdzie z innego modelu, ale musze miec pewnosc, ze ten rekord juz istnieje przy wypelnianiu tabelki z pubami. 
INSERT INTO pub4me_city (id, pl_name, en_name) VALUES ('CRACOW', 'Kraków', 'Cracow');

INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (1, 'Siesta Cafe', 'ul. Stolarska 6', 'CRACOW', 47);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (2, 'Singer', 'ul. Estery/róg ul. Izaaka', 'CRACOW', 129);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (3, 'Smocza Jama', 'ul. Miodowa 43', 'CRACOW', 351);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (4, 'SomePlace Else', 'ul. Powiśle 7', 'CRACOW', 241);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (5, 'Spokój', 'Ul. Bracka 3-5', 'CRACOW', 323);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (6, 'Sesja', 'ul. Warszawska 15', 'CRACOW', 283);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (7, 'Shisha Club', 'Mały Rynek 2', 'CRACOW', 273);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (8, 'Sport Bar', 'ul. Rakowicka 17', 'CRACOW', 222);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (9, 'SHOWTIME', 'Rynek Główny 28', 'CRACOW', 268);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (10, 'Sports Pub', 'al. 29 Listopada 57', 'CRACOW', 319);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (11, 'Sports Pub', 'ul. Grodzka 50', 'CRACOW', 349);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (12, 'Square Pub', 'ul. Grodzka 51', 'CRACOW', 334);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (13, 'Śródziemie', 'pl. Wszystkich Świętych 8', 'CRACOW', 132);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (14, 'Stalowe Magnolie', 'ul. Św. Jana 15', 'CRACOW', 187);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (15, 'Studio', 'ul. Budryka 4', 'CRACOW', 276);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (16, 'Studnia życzeń', 'pl. Nowy 6', 'CRACOW', 90);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (17, 'Szara Resto & Bar', 'Rynek Główny 6', 'CRACOW', 116);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (18, 'Tajemniczy ogród', 'ul. Bracka 3-5', 'CRACOW', 22);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (19, 'Tower Pub', 'ul. Grodzka 4', 'CRACOW', 124);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (20, 'Trambar', 'ul. Stolarska 11', 'CRACOW', 168);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (21, 'Transylwania', 'ul. Szeroka 9', 'CRACOW', 143);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (22, 'Tygiel Pub', 'ul. Senacka 9', 'CRACOW', 252);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (23, 'U Kacpra', 'ul. Sławkowska 2', 'CRACOW', 141);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (24, 'U Louisa', 'Rynek Główny 13', 'CRACOW', 75);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (25, 'Ulica Krokodyli', 'ul. Szeroka 30', 'CRACOW', 136);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (26, 'Rdza', 'ul. Bracka 3-5', 'CRACOW', 244);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (27, 'Re', 'ul. Krzyża 4', 'CRACOW', 115);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (28, 'Vesuvio Pizzeria - Restauracja', 'ul. Floriańska 38', 'CRACOW', 218);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (29, 'Warsztat Café', 'ul. Izaaka 3', 'CRACOW', 135);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (30, 'Winiarnia-Galeria Atelier', 'pl. Jana Matejki 7', 'CRACOW', 62);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (31, 'Reaktywacja', 'ul. Grodzka 34', 'CRACOW', 280);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (32, 'Ręce i Nogi Club', 'ul. Szewska 14', 'CRACOW', 239);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (33, 'Restauracja Nana', 'pl. Jana Matejki 3', 'CRACOW', 67);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (34, 'La Habana', 'ul. Miodowa 22', 'CRACOW', 159);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (35, 'Les Couleurs / Kolory', 'ul. Estery 10', 'CRACOW', 108);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (36, 'Kamienna Jazz Club', 'ul. Kamienna 17 (piwnica hali sportowej PK)', 'CRACOW', 237);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (37, 'Karlik - Klub studencki AGH', 'ul. Reymonta 17', 'CRACOW', 86);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (38, 'Katedra', 'ul. Poselska 9', 'CRACOW', 337);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (39, 'Kawiarnia Arka', 'Al. 29 Listopada 50', 'CRACOW', 296);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (40, 'Panorama Klub', 'Zwierzyniecka 50 (d.h. Jubilat ostatnie pietro)', 'CRACOW', 269);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (41, 'Paparazzi The Original Cafe Bar', 'ul. Mikołajska 9', 'CRACOW', 99);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (42, 'Pauza', 'ul. Floriańska 18/3', 'CRACOW', 154);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (43, 'Nic nowego', 'ul. Św. Krzyża 15', 'CRACOW', 181);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (44, 'Non Iron - Rugby Pub', 'ul. Św. Marka 27', 'CRACOW', 92);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (45, 'Nordic Pub', 'ul. św. Anny 5', 'CRACOW', 305);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (46, 'off.ceNtrum', 'ul. Wielopole 15/4 - II pietro', 'CRACOW', 311);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (47, 'Wręga', 'ul. Józefa 17', 'CRACOW', 336);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (48, 'Wyspiański - Restauracja-Klub Plastyków', 'ul. Łobzowska 3', 'CRACOW', 243);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (49, 'Żaczek Klub studencki', 'al. 3 Maja 5', 'CRACOW', 89);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (50, 'Zaraz Wracam', 'ul. Bożego Ciała 11', 'CRACOW', 240);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (51, 'Restauracja Pasieka', 'ul. Miodowa 25', 'CRACOW', 345);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (52, 'Retro Club', 'ul. Bożego Ciała 14', 'CRACOW', 352);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (53, 'Rotunda Centrum Kultury', 'ul. Oleandry 1', 'CRACOW', 79);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (54, 'Libido', 'ul. Warszauera 10', 'CRACOW', 328);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (55, 'Lizak', 'ul. Pijarska 11', 'CRACOW', 281);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (56, 'Kawiarnia Bambusowa', 'Rynek Główny 27', 'CRACOW', 73);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (57, 'Kawiarnia Naukowa', 'ul. Jakuba 29-31', 'CRACOW', 133);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (58, 'Kazamaty', 'ul. Dietla 50', 'CRACOW', 359);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (59, 'Kitsch', 'ul. Wielopole 15/4 II piętro', 'CRACOW', 267);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (60, 'Pergamin', 'ul. Bracka 3-5', 'CRACOW', 266);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (61, 'Piec Art (Acoustic Jazz Club)', 'ul. Szewska 12', 'CRACOW', 51);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (62, 'Piękny Pies', 'ul. Sławkowska 6a/1', 'CRACOW', 178);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (63, 'Oldsmobil Drink Bar & Pub', 'ul. Św. Tomasza 31', 'CRACOW', 32);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (64, 'Omerta', 'ul. Kupa 3', 'CRACOW', 332);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (65, 'Zaraz Wracam Tu', 'ul. Miodowa 53', 'CRACOW', 354);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (66, 'Ryba Babel', 'ul. Piastowska 47', 'CRACOW', 184);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (67, 'Loch Ness', 'ul. Warszawska 15-17', 'CRACOW', 61);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (68, 'Lokator', 'ul. Krakowska 10 (wejście od ul. Meiselsa)', 'CRACOW', 144);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (69, 'Klub Fabryka', 'ul. Zabłocie 23', 'CRACOW', 355);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (70, 'Klub Kulturalny', 'ul. Szewska 25', 'CRACOW', 176);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (71, 'Klub Obsesja', 'ul. Floriańska 24', 'CRACOW', 248);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (72, 'Pierwszy lokal na Stolarskiej po lewej stronie idąc od Małego Rynku', 'ul. Stolarska 6/1', 'CRACOW', 70);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (73, 'Playground', 'ul. Wielopole 15', 'CRACOW', 333);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (74, 'Pod Amorem - Pizzeria i Winiarnia', 'ul. Św. Tomasza 7', 'CRACOW', 46);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (75, 'Pod Złotą Pipą', 'ul. Floriańska 30', 'CRACOW', 170);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (76, 'Magiel na Kazimierzu', 'Ul. Meiselsa 9', 'CRACOW', 321);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (77, 'Masada', 'ul. Skawińska 2', 'CRACOW', 340);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (78, 'Łubu-dubu Klubokawiarnia', 'ul. Wielopole 15', 'CRACOW', 145);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (79, 'Kolanko No 6', 'Ul. Józefa 17', 'CRACOW', 316);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (80, 'Krakowska Piwnica Artystyczno - Muzyczna Faust', 'Rynek Główny 6', 'CRACOW', 160);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (81, 'Krawat Klub', 'Rynek Główny 29', 'CRACOW', 78);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (82, 'Podium', 'ul. Bracka 4', 'CRACOW', 76);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (83, 'Polibuda Pub', 'ul. Warszawska 17', 'CRACOW', 55);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (84, 'Portofino', 'ul. Wąska 2', 'CRACOW', 312);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (85, 'Prowincja', 'ul. Bracka 3', 'CRACOW', 146);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (86, 'Mechanoff Clab', 'ul. Estery 8', 'CRACOW', 134);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (87, 'Midgard', 'ul. Szpitalna 38', 'CRACOW', 293);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (88, 'Migrena Cafe', 'ul. Gołębia 3', 'CRACOW', 45);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (89, 'Kryjówka - Music Club & Restaurant', 'ul. Sławkowska 11', 'CRACOW', 49);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (90, 'Krzysztofory Kawiarnia', 'ul. Szczepańska 2', 'CRACOW', 192);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (91, 'Kwadrat Studenckie Centrum Kultury PK', 'ul. Skarżyńskiego 1', 'CRACOW', 257);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (92, 'Prozak', 'Pl. Dominikański 6', 'CRACOW', 246);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (93, 'Przychodnia Towarzyska', 'ul. Floriańska 53', 'CRACOW', 113);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (94, 'Przychodnia Towarzyska - Rewolucja', 'ul. Szewska 23', 'CRACOW', 274);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (95, 'Ministerstwo Klub Muzyczny', 'ul. Szpitalna 1', 'CRACOW', 223);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (96, 'Mleczarnia', 'ul. Meiselsa 20', 'CRACOW', 140);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (97, 'Jazz Faust Cafe ', 'ul. Szewska 21', 'CRACOW', 358);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (98, 'JazzRock Cafe', 'ul. Sławkowska 12', 'CRACOW', 53);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (99, 'Ptaszyl', 'ul. Szeroka 10', 'CRACOW', 137);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (100, 'Pub Galaktyka', 'ul. Pachońskiego 8', 'CRACOW', 350);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (101, 'Pub Popularny', 'ul. Grodzka 31', 'CRACOW', 114);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (102, 'Pub Społem', 'ul. Tomasza 4', 'CRACOW', 310);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (103, 'Młoda Nowa Polska', 'ul. Stolarska 1', 'CRACOW', 290);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (104, 'Moliere Centrum Kultury i Sztuki', 'ul. Szewska 4', 'CRACOW', 179);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (105, 'Gold Club Go-Go', 'ul. Księcia Józefa 71', 'CRACOW', 308);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (106, 'Gwarek - studencki klub muzyczny', 'ul. Reymonta 17', 'CRACOW', 220);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (107, 'Indigo', 'ul. Floriańska 26', 'CRACOW', 284);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (108, 'Inkwizytor', 'ul. Kanonicza 1', 'CRACOW', 197);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (109, 'Irish Pub Pod Papugami', 'ul. Św. Jana 18', 'CRACOW', 169);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (110, 'MS Grill bar', 'ul. Kurniki 6', 'CRACOW', 64);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (111, 'Hedonic Club & Lounge', 'ul. Szewska 9 (1 piętro)', 'CRACOW', 356);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (112, 'Hell & Heaven', 'ul. Brzozowa 8', 'CRACOW', 348);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (113, 'Huśtawka', 'ul. Św. Tomasza 9', 'CRACOW', 30);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (114, 'El Fuego', 'ul. Estery 5', 'CRACOW', 215);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (115, 'Enso Lounge', 'ul. Karmelicka 52', 'CRACOW', 327);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (116, 'Fantasy Park', 'ul. Aleja Pokoju 44', 'CRACOW', 302);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (117, 'Filmowa Cafe', 'al. Krasińskiego 34', 'CRACOW', 286);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (118, 'Folia Concept Club', 'Rynek Główny 30', 'CRACOW', 307);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (119, 'De Cafencja', 'ul. Sławkowska 4', 'CRACOW', 50);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (120, 'Drukarnia - Podgórze', 'ul. Nadwiślańska 1', 'CRACOW', 320);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (121, 'Frantic Music Club', 'ul. Szewska 5', 'CRACOW', 253);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (122, 'Café Larousse', 'ul. Św. Tomasza 22', 'CRACOW', 200);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (123, 'Café Numero', 'Rynek Główny 6', 'CRACOW', 74);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (124, 'Bafomet Club', 'ul. Szewska 9', 'CRACOW', 357);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (125, 'Baraka', 'ul. Warszauera 1 (pl. Nowy)', 'CRACOW', 229);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (126, 'Barrock', 'ul. Wąska 2', 'CRACOW', 272);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (127, 'Biesiada Klub', 'ul. Senacka 7', 'CRACOW', 125);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (128, 'Café Rękawka', 'ul. Brodzińskiego 4b', 'CRACOW', 216);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (129, 'Café Szafé', 'ul. Felicjanek 10', 'CRACOW', 156);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (130, 'Cafe Botanica', 'ul. Bracka 9', 'CRACOW', 1);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (131, 'Cafe Cabaret', 'ul. Jabłonowskich 6', 'CRACOW', 162);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (132, 'Black Gallery', 'ul. Mikołajska 24', 'CRACOW', 80);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (133, 'Bomba', 'Plac Szczepański 2/1', 'CRACOW', 360);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (134, 'Boogie Cafe Bar', 'ul. Szpitalna 9 (wejscie od ul. św.Tomasza)', 'CRACOW', 256);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (135, 'Boom Bar Rush', 'ul. Gołębia 6', 'CRACOW', 278);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (136, 'Cafe Gołębia 3', 'ul. Gołębia 3', 'CRACOW', 44);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (137, 'Cafe Magia', 'Pl. Mariacki 3', 'CRACOW', 331);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (138, 'Break Bilard Club', 'ul. Zbożowa 2', 'CRACOW', 353);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (139, 'Absynt', 'Ul. Miodowa 26', 'CRACOW', 294);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (140, 'Albo Tak', 'Mały Rynek 4', 'CRACOW', 247);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (141, 'Alchemia', 'ul. Estery 5', 'CRACOW', 225);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (142, 'Cafe Malaga', 'Rynek Główny 11', 'CRACOW', 130);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (143, 'Cafe Manekin', 'ul. Św. Tomasza 25', 'CRACOW', 26);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (144, 'Aleksander''s Chocolate Bar', 'Ul. Karmelicka 56', 'CRACOW', 324);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (145, 'Aloha Cafe', 'ul. Miodowa 28A', 'CRACOW', 339);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (146, 'Cafe Młynek', 'pl. Wolnica 7', 'CRACOW', 131);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (147, 'Cafe Premiera', 'ul. Michałowskiego 4', 'CRACOW', 211);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (148, 'Caffe Ragazzo', 'ul. Szewska 10', 'CRACOW', 207);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (149, 'Alter Ego', 'ul. Floriańska 13', 'CRACOW', 255);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (150, 'Ambasada Pub', 'ul. Starowiślna 12', 'CRACOW', 304);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (151, 'Art Club Błędne Koło', 'ul. Bracka 4 (I piętro, obok galerii)', 'CRACOW', 213);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (152, 'Camera Cafe', 'ul. Wiślna 5', 'CRACOW', 329);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (153, 'Camera Cafe Club', 'Plac Nowy 9', 'CRACOW', 330);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (154, 'Atmosfera', 'pl. Szczepański 7', 'CRACOW', 29);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (155, 'Awaria, Klub Muzyczny', 'ul. Mikołajska 9', 'CRACOW', 119);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (156, 'Carpe Diem', 'ul. Floriańska 33', 'CRACOW', 261);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (157, 'Casa Del La Pizza', 'Mały Rynek 2', 'CRACOW', 173);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (158, 'Chill Out Cafe', 'ul. Św. Jana 15', 'CRACOW', 193);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (159, 'Chocoffee Galeria Kawy i Czekolady', 'ul. Wiślna 8', 'CRACOW', 361);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (160, 'Cień Klub', 'ul. Św. Jana 15', 'CRACOW', 188);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (161, 'Club 07', 'Florianska 47', 'CRACOW', 298);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (162, 'Club Clu', 'ul. Szeroka 10', 'CRACOW', 288);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (163, 'Club VIP Night Club GoGo Kraków', 'ul. Filipa 7', 'CRACOW', 344);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (164, 'ClubOKOcafé', 'ul. Węgierska 1 (Podgórze)', 'CRACOW', 198);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (165, 'Coltrane Restaurant & Music Bar', 'ul. Biskupia 4', 'CRACOW', 338);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (166, 'Cudowne lata', 'ul. Karmelicka 43', 'CRACOW', 212);
INSERT INTO pub4me_pub (id, name, location, city_id, ext_service_id_kk) VALUES (167, 'Czasem trzeba', 'ul. Mikolajska 14', 'CRACOW', 202);